export * from "./StarsProps"
export * from "./GetImgProps"
export * from "./OnlyChildrenProps"
export * from "./ProductsProps"
export * from "./CardOfDealsProps"
export * from "./OnlyClassNameProps"
export * from "./ButtonProps"
export * from "./useArrowsControlProps"